# Code generated by scripts/generate.mjs from spec/openapi.yml; DO NOT EDIT.

from __future__ import annotations

from collections.abc import AsyncIterator, Awaitable, Callable, Iterator, Mapping, Sequence
from typing import Any, TypeVar

from . import models as m
from ._request import Call, RequestOptions, apaginate, encode_body, paginate

T = TypeVar("T")


class SyncOperations:
    def _send(self, call: Call, decode: Callable[[Any], T], options: RequestOptions | None) -> T:
        raise NotImplementedError

    def x402_discovery(self, *, options: RequestOptions | None = None) -> m.X402Discovery:
        """Operations payable with x402 and their prices."""
        r = Call("x402Discovery", "GET")
        r.path_literal(".well-known")
        r.path_literal("x402")
        return self._send(r, m.X402Discovery._from_json, options)

    def status(self, *, options: RequestOptions | None = None) -> m.StatusResponse:
        """Liveness and upstream health."""
        r = Call("status", "GET")
        r.path_literal("status")
        return self._send(r, m.StatusResponse._from_json, options)

    def key(self, *, options: RequestOptions | None = None) -> m.KeyInfo:
        """Plan and limits of the calling key."""
        r = Call("key", "GET")
        r.path_literal("key")
        return self._send(r, m.KeyInfo._from_json, options)

    def config(self, *, options: RequestOptions | None = None) -> m.Config:
        """Enumerations and defaults."""
        r = Call("config", "GET")
        r.path_literal("config")
        return self._send(r, m.Config._from_json, options)

    def chains(self, *, options: RequestOptions | None = None) -> m.ChainList:
        """Chains served right now."""
        r = Call("chains", "GET")
        r.path_literal("chains")
        return self._send(r, m.ChainList._from_json, options)

    def search(self, *, q: str, chains: Sequence[str] | None = None, limit: int | None = None, options: RequestOptions | None = None) -> m.SearchResponse:
        """Typeahead across tokens and pairs.

        Defaults: limit=8.
        """
        r = Call("search", "GET")
        r.path_literal("search")
        r.q_str("q", q, required=True, lo=1, hi=128)
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_int("limit", limit, lo=1, hi=50)
        return self._send(r, m.SearchResponse._from_json, options)

    def pairs(self, *, chains: Sequence[str] | None = None, q: str | None = None, protocols: Sequence[str] | None = None, dex_names: Sequence[str] | None = None, min_liquidity_usd: float | None = None, max_liquidity_usd: float | None = None, min_apr: float | None = None, max_apr: float | None = None, min_score: int | None = None, max_score: int | None = None, min_age_seconds: int | None = None, max_age_seconds: int | None = None, market_type: str | None = None, only_trustable: bool | None = None, max_deployed_pairs: int | None = None, sort: str | None = None, order: str | None = None, timeframe: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.PairPage:
        """Liquidity pair screener.

        Defaults: market_type="any", only_trustable=False, sort="liquidity", order="desc", timeframe="24h", limit=10.
        """
        r = Call("pairs", "GET")
        r.path_literal("pairs")
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_str("q", q, hi=128)
        r.q_list("protocols", protocols, hi=32)
        r.q_list("dex_names", dex_names, hi=32, item_hi=64)
        r.q_float("min_liquidity_usd", min_liquidity_usd, lo=0)
        r.q_float("max_liquidity_usd", max_liquidity_usd, lo=0)
        r.q_float("min_apr", min_apr)
        r.q_float("max_apr", max_apr)
        r.q_int("min_score", min_score, lo=0, hi=100)
        r.q_int("max_score", max_score, lo=0, hi=100)
        r.q_int("min_age_seconds", min_age_seconds, lo=0)
        r.q_int("max_age_seconds", max_age_seconds, lo=0)
        r.q_str("market_type", market_type)
        r.q_bool("only_trustable", only_trustable)
        r.q_int("max_deployed_pairs", max_deployed_pairs, lo=1)
        r.q_str("sort", sort)
        r.q_str("order", order)
        r.q_str("timeframe", timeframe)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.PairPage._from_json, options)

    def iter_pairs(self, *, chains: Sequence[str] | None = None, q: str | None = None, protocols: Sequence[str] | None = None, dex_names: Sequence[str] | None = None, min_liquidity_usd: float | None = None, max_liquidity_usd: float | None = None, min_apr: float | None = None, max_apr: float | None = None, min_score: int | None = None, max_score: int | None = None, min_age_seconds: int | None = None, max_age_seconds: int | None = None, market_type: str | None = None, only_trustable: bool | None = None, max_deployed_pairs: int | None = None, sort: str | None = None, order: str | None = None, timeframe: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.PairInfo]:
        """Every item of pairs, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.pairs(chains=chains, q=q, protocols=protocols, dex_names=dex_names, min_liquidity_usd=min_liquidity_usd, max_liquidity_usd=max_liquidity_usd, min_apr=min_apr, max_apr=max_apr, min_score=min_score, max_score=max_score, min_age_seconds=min_age_seconds, max_age_seconds=max_age_seconds, market_type=market_type, only_trustable=only_trustable, max_deployed_pairs=max_deployed_pairs, sort=sort, order=order, timeframe=timeframe, limit=limit, cursor=c, options=options), cursor, options)

    def pair(self, chain: str | int, address: str, *, options: RequestOptions | None = None) -> m.PairInfo:
        """One liquidity pair."""
        r = Call("pair", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("pairs")
        r.path_param("address", address, lo=1, hi=128)
        return self._send(r, m.PairInfo._from_json, options)

    def pair_trades(self, chain: str | int, address: str, *, tx_type: Sequence[str] | None = None, maker: str | None = None, from_: int | None = None, to: int | None = None, order: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.TradePage:
        """Trade tape of a pair.

        Defaults: order="desc", limit=10.
        """
        r = Call("pairTrades", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("pairs")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("trades")
        r.q_list("tx_type", tx_type, hi=8)
        r.q_str("maker", maker, lo=1, hi=128)
        r.q_int("from", from_, lo=0)
        r.q_int("to", to, lo=0)
        r.q_str("order", order)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.TradePage._from_json, options)

    def iter_pair_trades(self, chain: str | int, address: str, *, tx_type: Sequence[str] | None = None, maker: str | None = None, from_: int | None = None, to: int | None = None, order: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.Transaction]:
        """Every item of pair_trades, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.pair_trades(chain, address, tx_type=tx_type, maker=maker, from_=from_, to=to, order=order, limit=limit, cursor=c, options=options), cursor, options)

    def pair_candles(self, chain: str | int, address: str, *, res: str, from_: int, to: int, countback: int | None = None, currency: str | None = None, price_from_quote: bool | None = None, volume_from_quote: bool | None = None, options: RequestOptions | None = None) -> m.ChartCandles:
        """OHLCV candles.

        Defaults: currency="usd", price_from_quote=False, volume_from_quote=False.
        """
        r = Call("pairCandles", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("pairs")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("candles")
        r.q_str("res", res, required=True)
        r.q_int("from", from_, required=True, lo=0)
        r.q_int("to", to, required=True, lo=0)
        r.q_int("countback", countback, lo=1, hi=5000)
        r.q_str("currency", currency)
        r.q_bool("price_from_quote", price_from_quote)
        r.q_bool("volume_from_quote", volume_from_quote)
        return self._send(r, m.ChartCandles._from_json, options)

    def trending(self, *, chains: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.PairPage:
        """Trending pairs right now.

        Defaults: limit=10.
        """
        r = Call("trending", "GET")
        r.path_literal("trending")
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.PairPage._from_json, options)

    def iter_trending(self, *, chains: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.PairInfo]:
        """Every item of trending, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.trending(chains=chains, limit=limit, cursor=c, options=options), cursor, options)

    def pairs_new(self, *, chain: str, min_liquidity_usd: float | None = None, max_age_seconds: int | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.PairPage:
        """Newest pairs on one chain.

        Defaults: limit=10.
        """
        r = Call("pairsNew", "GET")
        r.path_literal("pairs")
        r.path_literal("new")
        r.q_str("chain", chain, required=True, lo=1, hi=32)
        r.q_float("min_liquidity_usd", min_liquidity_usd, lo=0)
        r.q_int("max_age_seconds", max_age_seconds, lo=0)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.PairPage._from_json, options)

    def iter_pairs_new(self, *, chain: str, min_liquidity_usd: float | None = None, max_age_seconds: int | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.PairInfo]:
        """Every item of pairs_new, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.pairs_new(chain=chain, min_liquidity_usd=min_liquidity_usd, max_age_seconds=max_age_seconds, limit=limit, cursor=c, options=options), cursor, options)

    def launchpad_tokens(self, *, chain: str, launch_status: str | None = None, launchpads: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.PairPage:
        """Launchpad launches by stage (new, bonding or graduated).

        Defaults: launch_status="new", limit=10.
        """
        r = Call("launchpadTokens", "GET")
        r.path_literal("launchpads")
        r.path_literal("tokens")
        r.q_str("chain", chain, required=True, lo=1, hi=32)
        r.q_str("launch_status", launch_status)
        r.q_list("launchpads", launchpads, hi=32, item_hi=64)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.PairPage._from_json, options)

    def iter_launchpad_tokens(self, *, chain: str, launch_status: str | None = None, launchpads: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.PairInfo]:
        """Every item of launchpad_tokens, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.launchpad_tokens(chain=chain, launch_status=launch_status, launchpads=launchpads, limit=limit, cursor=c, options=options), cursor, options)

    def pair_batch(self, *, items: Sequence[m.PairBatchRef | Mapping[str, Any]], options: RequestOptions | None = None) -> m.PairBatchResponse:
        """Many pairs in one call."""
        r = Call("pairBatch", "POST")
        r.path_literal("pairs")
        r.path_literal("batch")
        r.check_items("items", items, lo=1, hi=50)
        r.body = encode_body({"items": items})
        return self._send(r, m.PairBatchResponse._from_json, options)

    def perps(self, *, chains: Sequence[str] | None = None, q: str | None = None, sort: str | None = None, order: str | None = None, timeframe: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.PairPage:
        """Perpetual markets.

        Defaults: sort="volume", order="desc", timeframe="24h", limit=10.
        """
        r = Call("perps", "GET")
        r.path_literal("perps")
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_str("q", q, hi=128)
        r.q_str("sort", sort)
        r.q_str("order", order)
        r.q_str("timeframe", timeframe)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.PairPage._from_json, options)

    def iter_perps(self, *, chains: Sequence[str] | None = None, q: str | None = None, sort: str | None = None, order: str | None = None, timeframe: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.PairInfo]:
        """Every item of perps, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.perps(chains=chains, q=q, sort=sort, order=order, timeframe=timeframe, limit=limit, cursor=c, options=options), cursor, options)

    def perp_history(self, market: str, *, chain: str | None = None, from_: int | None = None, to: int | None = None, interval: str | None = None, options: RequestOptions | None = None) -> m.PerpHistory:
        """Open interest, funding and mark history of a perpetual.

        Defaults: chain="hyperliquid", interval="1h".
        """
        r = Call("perpHistory", "GET")
        r.path_literal("perps")
        r.path_param("market", market, lo=1, hi=128)
        r.path_literal("history")
        r.q_str("chain", chain, lo=1, hi=32)
        r.q_int("from", from_, lo=0)
        r.q_int("to", to, lo=0)
        r.q_str("interval", interval)
        return self._send(r, m.PerpHistory._from_json, options)

    def perp_liquidations(self, *, chain: str | None = None, market: str | None = None, from_: int | None = None, to: int | None = None, options: RequestOptions | None = None) -> m.PerpLiquidations:
        """Daily liquidations of a perpetual or a whole venue.

        Defaults: chain="hyperliquid".
        """
        r = Call("perpLiquidations", "GET")
        r.path_literal("perps")
        r.path_literal("liquidations")
        r.q_str("chain", chain, lo=1, hi=32)
        r.q_str("market", market, lo=1, hi=128)
        r.q_int("from", from_, lo=0)
        r.q_int("to", to, lo=0)
        return self._send(r, m.PerpLiquidations._from_json, options)

    def deployer_tokens(self, address: str, *, chains: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.DeployerLaunchPage:
        """Launches of one deployer, with its reputation card.

        Defaults: limit=10.
        """
        r = Call("deployerTokens", "GET")
        r.path_literal("deployers")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("tokens")
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.DeployerLaunchPage._from_json, options)

    def iter_deployer_tokens(self, address: str, *, chains: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.PairInfo]:
        """Every item of deployer_tokens, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.deployer_tokens(address, chains=chains, limit=limit, cursor=c, options=options), cursor, options)

    def token_by_address(self, chain: str | int, address: str, *, include_instances: bool | None = None, include_market: bool | None = None, options: RequestOptions | None = None) -> m.TokenInfo:
        """Canonical token by chain and address.

        Defaults: include_instances=True, include_market=True.
        """
        r = Call("tokenByAddress", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("tokens")
        r.path_param("address", address, lo=1, hi=128)
        r.q_bool("include_instances", include_instances)
        r.q_bool("include_market", include_market)
        return self._send(r, m.TokenInfo._from_json, options)

    def token_pairs(self, chain: str | int, address: str, *, limit: int | None = None, options: RequestOptions | None = None) -> m.PairPage:
        """Top pairs of a token by 24h volume.

        Defaults: limit=10.
        """
        r = Call("tokenPairs", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("tokens")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("pairs")
        r.q_int("limit", limit, lo=1, hi=10)
        return self._send(r, m.PairPage._from_json, options)

    def token_verdict(self, chain: str | int, address: str, *, options: RequestOptions | None = None) -> m.TokenVerdict:
        """Signed token verdict, submittable to the trust oracle."""
        r = Call("tokenVerdict", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("tokens")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("verdict")
        return self._send(r, m.TokenVerdict._from_json, options)

    def token_verdict_proof(self, chain: str | int, address: str, *, options: RequestOptions | None = None) -> m.TokenVerdictProof:
        """Merkle proof of a verdict at the last published epoch."""
        r = Call("tokenVerdictProof", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("tokens")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("proof")
        return self._send(r, m.TokenVerdictProof._from_json, options)

    def token_brief(self, chain: str | int, address: str, *, options: RequestOptions | None = None) -> m.TokenBrief:
        """Everything needed to decide about a token, in one call."""
        r = Call("tokenBrief", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("tokens")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("brief")
        return self._send(r, m.TokenBrief._from_json, options)

    def token_by_id(self, id: str, *, include_instances: bool | None = None, include_market: bool | None = None, options: RequestOptions | None = None) -> m.TokenInfo:
        """Canonical token by id.

        Defaults: include_instances=True, include_market=True.
        """
        r = Call("tokenByID", "GET")
        r.path_literal("tokens")
        r.path_param("id", id, uuid=True)
        r.q_bool("include_instances", include_instances)
        r.q_bool("include_market", include_market)
        return self._send(r, m.TokenInfo._from_json, options)

    def token_by_slug(self, slug: str, *, include_instances: bool | None = None, include_market: bool | None = None, options: RequestOptions | None = None) -> m.TokenInfo:
        """Canonical token by slug.

        Defaults: include_instances=True, include_market=True.
        """
        r = Call("tokenBySlug", "GET")
        r.path_literal("tokens")
        r.path_literal("by-slug")
        r.path_param("slug", slug, lo=1, hi=128)
        r.q_bool("include_instances", include_instances)
        r.q_bool("include_market", include_market)
        return self._send(r, m.TokenInfo._from_json, options)

    def tokens(self, *, q: str | None = None, chains: Sequence[str] | None = None, categories: Sequence[str] | None = None, sort: str | None = None, order: str | None = None, min_liquidity_usd: float | None = None, max_liquidity_usd: float | None = None, min_volume_usd: float | None = None, max_volume_usd: float | None = None, min_market_cap_usd: float | None = None, max_market_cap_usd: float | None = None, min_fdv_usd: float | None = None, max_fdv_usd: float | None = None, min_age_seconds: int | None = None, max_age_seconds: int | None = None, min_score: int | None = None, max_score: int | None = None, min_holders: int | None = None, max_holders: int | None = None, include_instances: bool | None = None, include_market: bool | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.TokenPage:
        """Token market list, ranked by market cap.

        Defaults: sort="market_cap", order="desc", include_instances=False, include_market=False, limit=10.
        """
        r = Call("tokens", "GET")
        r.path_literal("tokens")
        r.q_str("q", q, hi=128)
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_list("categories", categories, hi=32, item_lo=1, item_hi=64)
        r.q_str("sort", sort)
        r.q_str("order", order)
        r.q_float("min_liquidity_usd", min_liquidity_usd, lo=0)
        r.q_float("max_liquidity_usd", max_liquidity_usd, lo=0)
        r.q_float("min_volume_usd", min_volume_usd, lo=0)
        r.q_float("max_volume_usd", max_volume_usd, lo=0)
        r.q_float("min_market_cap_usd", min_market_cap_usd, lo=0)
        r.q_float("max_market_cap_usd", max_market_cap_usd, lo=0)
        r.q_float("min_fdv_usd", min_fdv_usd, lo=0)
        r.q_float("max_fdv_usd", max_fdv_usd, lo=0)
        r.q_int("min_age_seconds", min_age_seconds, lo=0)
        r.q_int("max_age_seconds", max_age_seconds, lo=0)
        r.q_int("min_score", min_score, lo=0, hi=100)
        r.q_int("max_score", max_score, lo=0, hi=100)
        r.q_int("min_holders", min_holders, lo=0)
        r.q_int("max_holders", max_holders, lo=0)
        r.q_bool("include_instances", include_instances)
        r.q_bool("include_market", include_market)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.TokenPage._from_json, options)

    def iter_tokens(self, *, q: str | None = None, chains: Sequence[str] | None = None, categories: Sequence[str] | None = None, sort: str | None = None, order: str | None = None, min_liquidity_usd: float | None = None, max_liquidity_usd: float | None = None, min_volume_usd: float | None = None, max_volume_usd: float | None = None, min_market_cap_usd: float | None = None, max_market_cap_usd: float | None = None, min_fdv_usd: float | None = None, max_fdv_usd: float | None = None, min_age_seconds: int | None = None, max_age_seconds: int | None = None, min_score: int | None = None, max_score: int | None = None, min_holders: int | None = None, max_holders: int | None = None, include_instances: bool | None = None, include_market: bool | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.TokenInfo]:
        """Every item of tokens, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.tokens(q=q, chains=chains, categories=categories, sort=sort, order=order, min_liquidity_usd=min_liquidity_usd, max_liquidity_usd=max_liquidity_usd, min_volume_usd=min_volume_usd, max_volume_usd=max_volume_usd, min_market_cap_usd=min_market_cap_usd, max_market_cap_usd=max_market_cap_usd, min_fdv_usd=min_fdv_usd, max_fdv_usd=max_fdv_usd, min_age_seconds=min_age_seconds, max_age_seconds=max_age_seconds, min_score=min_score, max_score=max_score, min_holders=min_holders, max_holders=max_holders, include_instances=include_instances, include_market=include_market, limit=limit, cursor=c, options=options), cursor, options)

    def token_batch(self, *, items: Sequence[m.TokenBatchRef | Mapping[str, Any]], options: RequestOptions | None = None) -> m.TokenBatchResponse:
        """Resolve many tokens at once."""
        r = Call("tokenBatch", "POST")
        r.path_literal("tokens")
        r.path_literal("batch")
        r.check_items("items", items, lo=1, hi=200)
        r.body = encode_body({"items": items})
        return self._send(r, m.TokenBatchResponse._from_json, options)

    def token_holders(self, chain: str | int, address: str, *, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.TokenHolderPage:
        """Top holders of a token.

        Defaults: limit=10.
        """
        r = Call("tokenHolders", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("tokens")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("holders")
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.TokenHolderPage._from_json, options)

    def iter_token_holders(self, chain: str | int, address: str, *, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.TokenHolder]:
        """Every item of token_holders, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.token_holders(chain, address, limit=limit, cursor=c, options=options), cursor, options)

    def token_traders(self, chain: str | int, address: str, *, sort: str | None = None, state: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.TokenTraderPage:
        """Wallets that traded a token, with their PNL on it.

        Defaults: sort="realized_pnl", state="any", limit=10.
        """
        r = Call("tokenTraders", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("tokens")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("traders")
        r.q_str("sort", sort)
        r.q_str("state", state)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.TokenTraderPage._from_json, options)

    def iter_token_traders(self, chain: str | int, address: str, *, sort: str | None = None, state: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.TokenTrader]:
        """Every item of token_traders, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.token_traders(chain, address, sort=sort, state=state, limit=limit, cursor=c, options=options), cursor, options)

    def farms(self, *, chains: Sequence[str], q: str | None = None, factories: Sequence[str] | None = None, sort: str | None = None, order: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.FarmPage:
        """Yield farm screener.

        Defaults: sort="tvl", order="desc", limit=10.
        """
        r = Call("farms", "GET")
        r.path_literal("farms")
        r.q_list("chains", chains, required=True, lo=1, hi=8, item_lo=1, item_hi=32)
        r.q_str("q", q, hi=128)
        r.q_list("factories", factories, hi=32, item_lo=1, item_hi=128)
        r.q_str("sort", sort)
        r.q_str("order", order)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.FarmPage._from_json, options)

    def iter_farms(self, *, chains: Sequence[str], q: str | None = None, factories: Sequence[str] | None = None, sort: str | None = None, order: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.FarmInfo]:
        """Every item of farms, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.farms(chains=chains, q=q, factories=factories, sort=sort, order=order, limit=limit, cursor=c, options=options), cursor, options)

    def farm(self, chain: str | int, address: str, *, options: RequestOptions | None = None) -> m.FarmInfo:
        """One yield farm."""
        r = Call("farm", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("farms")
        r.path_param("address", address, lo=1, hi=128)
        return self._send(r, m.FarmInfo._from_json, options)

    def wallets(self, *, chain: str, window: str | None = None, sort: str | None = None, order: str | None = None, min_total_pnl_usd: float | None = None, min_realized_pnl_usd: float | None = None, min_volume_usd: float | None = None, min_win_rate: float | None = None, min_trades: int | None = None, max_avg_hold_seconds: int | None = None, min_user_score: int | None = None, no_abuse_evidence: bool | None = None, only_copy_eligible: bool | None = None, exclude_bots: bool | None = None, tiers: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.WalletPage:
        """Rank traders on one chain.

        Defaults: window="30d", sort="total_pnl", order="desc", limit=10.
        """
        r = Call("wallets", "GET")
        r.path_literal("wallets")
        r.q_str("chain", chain, required=True, lo=1, hi=32)
        r.q_str("window", window)
        r.q_str("sort", sort)
        r.q_str("order", order)
        r.q_float("min_total_pnl_usd", min_total_pnl_usd)
        r.q_float("min_realized_pnl_usd", min_realized_pnl_usd)
        r.q_float("min_volume_usd", min_volume_usd)
        r.q_float("min_win_rate", min_win_rate, lo=0, hi=1)
        r.q_int("min_trades", min_trades)
        r.q_int("max_avg_hold_seconds", max_avg_hold_seconds)
        r.q_int("min_user_score", min_user_score, lo=0, hi=100)
        r.q_bool("no_abuse_evidence", no_abuse_evidence)
        r.q_bool("only_copy_eligible", only_copy_eligible)
        r.q_bool("exclude_bots", exclude_bots)
        r.q_list("tiers", tiers, hi=8, item_hi=32)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.WalletPage._from_json, options)

    def iter_wallets(self, *, chain: str, window: str | None = None, sort: str | None = None, order: str | None = None, min_total_pnl_usd: float | None = None, min_realized_pnl_usd: float | None = None, min_volume_usd: float | None = None, min_win_rate: float | None = None, min_trades: int | None = None, max_avg_hold_seconds: int | None = None, min_user_score: int | None = None, no_abuse_evidence: bool | None = None, only_copy_eligible: bool | None = None, exclude_bots: bool | None = None, tiers: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.WalletListItem]:
        """Every item of wallets, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.wallets(chain=chain, window=window, sort=sort, order=order, min_total_pnl_usd=min_total_pnl_usd, min_realized_pnl_usd=min_realized_pnl_usd, min_volume_usd=min_volume_usd, min_win_rate=min_win_rate, min_trades=min_trades, max_avg_hold_seconds=max_avg_hold_seconds, min_user_score=min_user_score, no_abuse_evidence=no_abuse_evidence, only_copy_eligible=only_copy_eligible, exclude_bots=exclude_bots, tiers=tiers, limit=limit, cursor=c, options=options), cursor, options)

    def wallet_stats(self, *, chains: Sequence[str] | None = None, options: RequestOptions | None = None) -> m.WalletStats:
        """Trader population per chain."""
        r = Call("walletStats", "GET")
        r.path_literal("wallets")
        r.path_literal("stats")
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        return self._send(r, m.WalletStats._from_json, options)

    def wallet_labels_batch(self, *, chain: str | int, addresses: Sequence[str], options: RequestOptions | None = None) -> m.WalletLabelList:
        """Behaviour labels for many wallets."""
        r = Call("walletLabelsBatch", "POST")
        r.path_literal("wallets")
        r.path_literal("labels")
        r.path_literal("batch")
        r.check_items("addresses", addresses, lo=1, hi=200)
        r.body = encode_body({"chain": str(chain), "addresses": addresses})
        return self._send(r, m.WalletLabelList._from_json, options)

    def wallet_overview(self, address: str, *, chains: Sequence[str] | None = None, window: str | None = None, options: RequestOptions | None = None) -> m.WalletOverview:
        """One wallet across every chain it traded.

        Defaults: window="30d".
        """
        r = Call("walletOverview", "GET")
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("overview")
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_str("window", window)
        return self._send(r, m.WalletOverview._from_json, options)

    def leaderboard(self, *, scope: str, chain: str | None = None, chains: Sequence[str] | None = None, seasonal: bool | None = None, season: int | None = None, limit: int | None = None, options: RequestOptions | None = None) -> m.Leaderboard:
        """Chain and DEX protocol boards.

        Defaults: limit=50.
        """
        r = Call("leaderboard", "GET")
        r.path_literal("leaderboard")
        r.q_str("scope", scope, required=True)
        r.q_str("chain", chain, lo=1, hi=32)
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_bool("seasonal", seasonal)
        r.q_int("season", season, lo=0)
        r.q_int("limit", limit, lo=1, hi=200)
        return self._send(r, m.Leaderboard._from_json, options)

    def wallet_profile(self, chain: str | int, address: str, *, options: RequestOptions | None = None) -> m.WalletProfile:
        """Trader profile with metrics for every window."""
        r = Call("walletProfile", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        return self._send(r, m.WalletProfile._from_json, options)

    def wallet_positions(self, chain: str | int, address: str, *, state: str | None = None, sort: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.WalletPositionPage:
        """Open and closed positions of a wallet.

        Defaults: state="any", sort="token", limit=10.
        """
        r = Call("walletPositions", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("positions")
        r.q_str("state", state)
        r.q_str("sort", sort)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.WalletPositionPage._from_json, options)

    def iter_wallet_positions(self, chain: str | int, address: str, *, state: str | None = None, sort: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.WalletPosition]:
        """Every item of wallet_positions, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.wallet_positions(chain, address, state=state, sort=sort, limit=limit, cursor=c, options=options), cursor, options)

    def wallet_trades(self, chain: str | int, address: str, *, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.WalletTradePage:
        """Raw trade history of a wallet.

        Defaults: limit=10.
        """
        r = Call("walletTrades", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("trades")
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.WalletTradePage._from_json, options)

    def iter_wallet_trades(self, chain: str | int, address: str, *, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.WalletTrade]:
        """Every item of wallet_trades, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.wallet_trades(chain, address, limit=limit, cursor=c, options=options), cursor, options)

    def wallet_chart(self, chain: str | int, address: str, *, window: str | None = None, options: RequestOptions | None = None) -> m.WalletChart:
        """Wallet performance series — PNL and ROI.

        Defaults: window="30d".
        """
        r = Call("walletChart", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("chart")
        r.q_str("window", window)
        return self._send(r, m.WalletChart._from_json, options)

    def wallet_best_trades(self, chain: str | int, address: str, *, window: str | None = None, limit: int | None = None, options: RequestOptions | None = None) -> m.WalletBestTrades:
        """Best and worst closed trades of a wallet.

        Defaults: window="30d", limit=10.
        """
        r = Call("walletBestTrades", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("best-trades")
        r.q_str("window", window)
        r.q_int("limit", limit, lo=1, hi=100)
        return self._send(r, m.WalletBestTrades._from_json, options)

    def wallet_rounds(self, chain: str | int, address: str, *, token: str | None = None, state: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.WalletRoundPage:
        """Position rounds — one entry and exit cycle per row.

        Defaults: state="any", limit=10.
        """
        r = Call("walletRounds", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("rounds")
        r.q_str("token", token, lo=1, hi=128)
        r.q_str("state", state)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return self._send(r, m.WalletRoundPage._from_json, options)

    def iter_wallet_rounds(self, chain: str | int, address: str, *, token: str | None = None, state: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> Iterator[m.WalletPositionRound]:
        """Every item of wallet_rounds, fetching the next page only when the previous one is used up."""
        return paginate(lambda c: self.wallet_rounds(chain, address, token=token, state=state, limit=limit, cursor=c, options=options), cursor, options)

    def wallet_funding(self, chain: str | int, address: str, *, options: RequestOptions | None = None) -> m.WalletFunding:
        """Who funded a wallet."""
        r = Call("walletFunding", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("funding")
        return self._send(r, m.WalletFunding._from_json, options)

    def oracle_prices(self, *, ids: Sequence[str], options: RequestOptions | None = None) -> m.OraclePriceList:
        """Latest oracle prices by feed id."""
        r = Call("oraclePrices", "GET")
        r.path_literal("prices")
        r.q_list("ids", ids, required=True, lo=1, hi=100, item_lo=64, item_hi=66)
        return self._send(r, m.OraclePriceList._from_json, options)

    def oracle_prices_at(self, *, ids: Sequence[str], ts: int, options: RequestOptions | None = None) -> m.OraclePriceList:
        """Oracle prices at a past moment."""
        r = Call("oraclePricesAt", "GET")
        r.path_literal("prices")
        r.path_literal("at")
        r.q_list("ids", ids, required=True, lo=1, hi=100, item_lo=64, item_hi=66)
        r.q_int("ts", ts, required=True, lo=1)
        return self._send(r, m.OraclePriceList._from_json, options)


class AsyncOperations:
    def _send(self, call: Call, decode: Callable[[Any], T], options: RequestOptions | None) -> Awaitable[T]:
        raise NotImplementedError

    async def x402_discovery(self, *, options: RequestOptions | None = None) -> m.X402Discovery:
        """Operations payable with x402 and their prices."""
        r = Call("x402Discovery", "GET")
        r.path_literal(".well-known")
        r.path_literal("x402")
        return await self._send(r, m.X402Discovery._from_json, options)

    async def status(self, *, options: RequestOptions | None = None) -> m.StatusResponse:
        """Liveness and upstream health."""
        r = Call("status", "GET")
        r.path_literal("status")
        return await self._send(r, m.StatusResponse._from_json, options)

    async def key(self, *, options: RequestOptions | None = None) -> m.KeyInfo:
        """Plan and limits of the calling key."""
        r = Call("key", "GET")
        r.path_literal("key")
        return await self._send(r, m.KeyInfo._from_json, options)

    async def config(self, *, options: RequestOptions | None = None) -> m.Config:
        """Enumerations and defaults."""
        r = Call("config", "GET")
        r.path_literal("config")
        return await self._send(r, m.Config._from_json, options)

    async def chains(self, *, options: RequestOptions | None = None) -> m.ChainList:
        """Chains served right now."""
        r = Call("chains", "GET")
        r.path_literal("chains")
        return await self._send(r, m.ChainList._from_json, options)

    async def search(self, *, q: str, chains: Sequence[str] | None = None, limit: int | None = None, options: RequestOptions | None = None) -> m.SearchResponse:
        """Typeahead across tokens and pairs.

        Defaults: limit=8.
        """
        r = Call("search", "GET")
        r.path_literal("search")
        r.q_str("q", q, required=True, lo=1, hi=128)
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_int("limit", limit, lo=1, hi=50)
        return await self._send(r, m.SearchResponse._from_json, options)

    async def pairs(self, *, chains: Sequence[str] | None = None, q: str | None = None, protocols: Sequence[str] | None = None, dex_names: Sequence[str] | None = None, min_liquidity_usd: float | None = None, max_liquidity_usd: float | None = None, min_apr: float | None = None, max_apr: float | None = None, min_score: int | None = None, max_score: int | None = None, min_age_seconds: int | None = None, max_age_seconds: int | None = None, market_type: str | None = None, only_trustable: bool | None = None, max_deployed_pairs: int | None = None, sort: str | None = None, order: str | None = None, timeframe: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.PairPage:
        """Liquidity pair screener.

        Defaults: market_type="any", only_trustable=False, sort="liquidity", order="desc", timeframe="24h", limit=10.
        """
        r = Call("pairs", "GET")
        r.path_literal("pairs")
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_str("q", q, hi=128)
        r.q_list("protocols", protocols, hi=32)
        r.q_list("dex_names", dex_names, hi=32, item_hi=64)
        r.q_float("min_liquidity_usd", min_liquidity_usd, lo=0)
        r.q_float("max_liquidity_usd", max_liquidity_usd, lo=0)
        r.q_float("min_apr", min_apr)
        r.q_float("max_apr", max_apr)
        r.q_int("min_score", min_score, lo=0, hi=100)
        r.q_int("max_score", max_score, lo=0, hi=100)
        r.q_int("min_age_seconds", min_age_seconds, lo=0)
        r.q_int("max_age_seconds", max_age_seconds, lo=0)
        r.q_str("market_type", market_type)
        r.q_bool("only_trustable", only_trustable)
        r.q_int("max_deployed_pairs", max_deployed_pairs, lo=1)
        r.q_str("sort", sort)
        r.q_str("order", order)
        r.q_str("timeframe", timeframe)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.PairPage._from_json, options)

    def iter_pairs(self, *, chains: Sequence[str] | None = None, q: str | None = None, protocols: Sequence[str] | None = None, dex_names: Sequence[str] | None = None, min_liquidity_usd: float | None = None, max_liquidity_usd: float | None = None, min_apr: float | None = None, max_apr: float | None = None, min_score: int | None = None, max_score: int | None = None, min_age_seconds: int | None = None, max_age_seconds: int | None = None, market_type: str | None = None, only_trustable: bool | None = None, max_deployed_pairs: int | None = None, sort: str | None = None, order: str | None = None, timeframe: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.PairInfo]:
        """Every item of pairs, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.pairs(chains=chains, q=q, protocols=protocols, dex_names=dex_names, min_liquidity_usd=min_liquidity_usd, max_liquidity_usd=max_liquidity_usd, min_apr=min_apr, max_apr=max_apr, min_score=min_score, max_score=max_score, min_age_seconds=min_age_seconds, max_age_seconds=max_age_seconds, market_type=market_type, only_trustable=only_trustable, max_deployed_pairs=max_deployed_pairs, sort=sort, order=order, timeframe=timeframe, limit=limit, cursor=c, options=options), cursor, options)

    async def pair(self, chain: str | int, address: str, *, options: RequestOptions | None = None) -> m.PairInfo:
        """One liquidity pair."""
        r = Call("pair", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("pairs")
        r.path_param("address", address, lo=1, hi=128)
        return await self._send(r, m.PairInfo._from_json, options)

    async def pair_trades(self, chain: str | int, address: str, *, tx_type: Sequence[str] | None = None, maker: str | None = None, from_: int | None = None, to: int | None = None, order: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.TradePage:
        """Trade tape of a pair.

        Defaults: order="desc", limit=10.
        """
        r = Call("pairTrades", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("pairs")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("trades")
        r.q_list("tx_type", tx_type, hi=8)
        r.q_str("maker", maker, lo=1, hi=128)
        r.q_int("from", from_, lo=0)
        r.q_int("to", to, lo=0)
        r.q_str("order", order)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.TradePage._from_json, options)

    def iter_pair_trades(self, chain: str | int, address: str, *, tx_type: Sequence[str] | None = None, maker: str | None = None, from_: int | None = None, to: int | None = None, order: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.Transaction]:
        """Every item of pair_trades, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.pair_trades(chain, address, tx_type=tx_type, maker=maker, from_=from_, to=to, order=order, limit=limit, cursor=c, options=options), cursor, options)

    async def pair_candles(self, chain: str | int, address: str, *, res: str, from_: int, to: int, countback: int | None = None, currency: str | None = None, price_from_quote: bool | None = None, volume_from_quote: bool | None = None, options: RequestOptions | None = None) -> m.ChartCandles:
        """OHLCV candles.

        Defaults: currency="usd", price_from_quote=False, volume_from_quote=False.
        """
        r = Call("pairCandles", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("pairs")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("candles")
        r.q_str("res", res, required=True)
        r.q_int("from", from_, required=True, lo=0)
        r.q_int("to", to, required=True, lo=0)
        r.q_int("countback", countback, lo=1, hi=5000)
        r.q_str("currency", currency)
        r.q_bool("price_from_quote", price_from_quote)
        r.q_bool("volume_from_quote", volume_from_quote)
        return await self._send(r, m.ChartCandles._from_json, options)

    async def trending(self, *, chains: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.PairPage:
        """Trending pairs right now.

        Defaults: limit=10.
        """
        r = Call("trending", "GET")
        r.path_literal("trending")
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.PairPage._from_json, options)

    def iter_trending(self, *, chains: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.PairInfo]:
        """Every item of trending, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.trending(chains=chains, limit=limit, cursor=c, options=options), cursor, options)

    async def pairs_new(self, *, chain: str, min_liquidity_usd: float | None = None, max_age_seconds: int | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.PairPage:
        """Newest pairs on one chain.

        Defaults: limit=10.
        """
        r = Call("pairsNew", "GET")
        r.path_literal("pairs")
        r.path_literal("new")
        r.q_str("chain", chain, required=True, lo=1, hi=32)
        r.q_float("min_liquidity_usd", min_liquidity_usd, lo=0)
        r.q_int("max_age_seconds", max_age_seconds, lo=0)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.PairPage._from_json, options)

    def iter_pairs_new(self, *, chain: str, min_liquidity_usd: float | None = None, max_age_seconds: int | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.PairInfo]:
        """Every item of pairs_new, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.pairs_new(chain=chain, min_liquidity_usd=min_liquidity_usd, max_age_seconds=max_age_seconds, limit=limit, cursor=c, options=options), cursor, options)

    async def launchpad_tokens(self, *, chain: str, launch_status: str | None = None, launchpads: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.PairPage:
        """Launchpad launches by stage (new, bonding or graduated).

        Defaults: launch_status="new", limit=10.
        """
        r = Call("launchpadTokens", "GET")
        r.path_literal("launchpads")
        r.path_literal("tokens")
        r.q_str("chain", chain, required=True, lo=1, hi=32)
        r.q_str("launch_status", launch_status)
        r.q_list("launchpads", launchpads, hi=32, item_hi=64)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.PairPage._from_json, options)

    def iter_launchpad_tokens(self, *, chain: str, launch_status: str | None = None, launchpads: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.PairInfo]:
        """Every item of launchpad_tokens, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.launchpad_tokens(chain=chain, launch_status=launch_status, launchpads=launchpads, limit=limit, cursor=c, options=options), cursor, options)

    async def pair_batch(self, *, items: Sequence[m.PairBatchRef | Mapping[str, Any]], options: RequestOptions | None = None) -> m.PairBatchResponse:
        """Many pairs in one call."""
        r = Call("pairBatch", "POST")
        r.path_literal("pairs")
        r.path_literal("batch")
        r.check_items("items", items, lo=1, hi=50)
        r.body = encode_body({"items": items})
        return await self._send(r, m.PairBatchResponse._from_json, options)

    async def perps(self, *, chains: Sequence[str] | None = None, q: str | None = None, sort: str | None = None, order: str | None = None, timeframe: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.PairPage:
        """Perpetual markets.

        Defaults: sort="volume", order="desc", timeframe="24h", limit=10.
        """
        r = Call("perps", "GET")
        r.path_literal("perps")
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_str("q", q, hi=128)
        r.q_str("sort", sort)
        r.q_str("order", order)
        r.q_str("timeframe", timeframe)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.PairPage._from_json, options)

    def iter_perps(self, *, chains: Sequence[str] | None = None, q: str | None = None, sort: str | None = None, order: str | None = None, timeframe: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.PairInfo]:
        """Every item of perps, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.perps(chains=chains, q=q, sort=sort, order=order, timeframe=timeframe, limit=limit, cursor=c, options=options), cursor, options)

    async def perp_history(self, market: str, *, chain: str | None = None, from_: int | None = None, to: int | None = None, interval: str | None = None, options: RequestOptions | None = None) -> m.PerpHistory:
        """Open interest, funding and mark history of a perpetual.

        Defaults: chain="hyperliquid", interval="1h".
        """
        r = Call("perpHistory", "GET")
        r.path_literal("perps")
        r.path_param("market", market, lo=1, hi=128)
        r.path_literal("history")
        r.q_str("chain", chain, lo=1, hi=32)
        r.q_int("from", from_, lo=0)
        r.q_int("to", to, lo=0)
        r.q_str("interval", interval)
        return await self._send(r, m.PerpHistory._from_json, options)

    async def perp_liquidations(self, *, chain: str | None = None, market: str | None = None, from_: int | None = None, to: int | None = None, options: RequestOptions | None = None) -> m.PerpLiquidations:
        """Daily liquidations of a perpetual or a whole venue.

        Defaults: chain="hyperliquid".
        """
        r = Call("perpLiquidations", "GET")
        r.path_literal("perps")
        r.path_literal("liquidations")
        r.q_str("chain", chain, lo=1, hi=32)
        r.q_str("market", market, lo=1, hi=128)
        r.q_int("from", from_, lo=0)
        r.q_int("to", to, lo=0)
        return await self._send(r, m.PerpLiquidations._from_json, options)

    async def deployer_tokens(self, address: str, *, chains: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.DeployerLaunchPage:
        """Launches of one deployer, with its reputation card.

        Defaults: limit=10.
        """
        r = Call("deployerTokens", "GET")
        r.path_literal("deployers")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("tokens")
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.DeployerLaunchPage._from_json, options)

    def iter_deployer_tokens(self, address: str, *, chains: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.PairInfo]:
        """Every item of deployer_tokens, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.deployer_tokens(address, chains=chains, limit=limit, cursor=c, options=options), cursor, options)

    async def token_by_address(self, chain: str | int, address: str, *, include_instances: bool | None = None, include_market: bool | None = None, options: RequestOptions | None = None) -> m.TokenInfo:
        """Canonical token by chain and address.

        Defaults: include_instances=True, include_market=True.
        """
        r = Call("tokenByAddress", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("tokens")
        r.path_param("address", address, lo=1, hi=128)
        r.q_bool("include_instances", include_instances)
        r.q_bool("include_market", include_market)
        return await self._send(r, m.TokenInfo._from_json, options)

    async def token_pairs(self, chain: str | int, address: str, *, limit: int | None = None, options: RequestOptions | None = None) -> m.PairPage:
        """Top pairs of a token by 24h volume.

        Defaults: limit=10.
        """
        r = Call("tokenPairs", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("tokens")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("pairs")
        r.q_int("limit", limit, lo=1, hi=10)
        return await self._send(r, m.PairPage._from_json, options)

    async def token_verdict(self, chain: str | int, address: str, *, options: RequestOptions | None = None) -> m.TokenVerdict:
        """Signed token verdict, submittable to the trust oracle."""
        r = Call("tokenVerdict", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("tokens")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("verdict")
        return await self._send(r, m.TokenVerdict._from_json, options)

    async def token_verdict_proof(self, chain: str | int, address: str, *, options: RequestOptions | None = None) -> m.TokenVerdictProof:
        """Merkle proof of a verdict at the last published epoch."""
        r = Call("tokenVerdictProof", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("tokens")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("proof")
        return await self._send(r, m.TokenVerdictProof._from_json, options)

    async def token_brief(self, chain: str | int, address: str, *, options: RequestOptions | None = None) -> m.TokenBrief:
        """Everything needed to decide about a token, in one call."""
        r = Call("tokenBrief", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("tokens")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("brief")
        return await self._send(r, m.TokenBrief._from_json, options)

    async def token_by_id(self, id: str, *, include_instances: bool | None = None, include_market: bool | None = None, options: RequestOptions | None = None) -> m.TokenInfo:
        """Canonical token by id.

        Defaults: include_instances=True, include_market=True.
        """
        r = Call("tokenByID", "GET")
        r.path_literal("tokens")
        r.path_param("id", id, uuid=True)
        r.q_bool("include_instances", include_instances)
        r.q_bool("include_market", include_market)
        return await self._send(r, m.TokenInfo._from_json, options)

    async def token_by_slug(self, slug: str, *, include_instances: bool | None = None, include_market: bool | None = None, options: RequestOptions | None = None) -> m.TokenInfo:
        """Canonical token by slug.

        Defaults: include_instances=True, include_market=True.
        """
        r = Call("tokenBySlug", "GET")
        r.path_literal("tokens")
        r.path_literal("by-slug")
        r.path_param("slug", slug, lo=1, hi=128)
        r.q_bool("include_instances", include_instances)
        r.q_bool("include_market", include_market)
        return await self._send(r, m.TokenInfo._from_json, options)

    async def tokens(self, *, q: str | None = None, chains: Sequence[str] | None = None, categories: Sequence[str] | None = None, sort: str | None = None, order: str | None = None, min_liquidity_usd: float | None = None, max_liquidity_usd: float | None = None, min_volume_usd: float | None = None, max_volume_usd: float | None = None, min_market_cap_usd: float | None = None, max_market_cap_usd: float | None = None, min_fdv_usd: float | None = None, max_fdv_usd: float | None = None, min_age_seconds: int | None = None, max_age_seconds: int | None = None, min_score: int | None = None, max_score: int | None = None, min_holders: int | None = None, max_holders: int | None = None, include_instances: bool | None = None, include_market: bool | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.TokenPage:
        """Token market list, ranked by market cap.

        Defaults: sort="market_cap", order="desc", include_instances=False, include_market=False, limit=10.
        """
        r = Call("tokens", "GET")
        r.path_literal("tokens")
        r.q_str("q", q, hi=128)
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_list("categories", categories, hi=32, item_lo=1, item_hi=64)
        r.q_str("sort", sort)
        r.q_str("order", order)
        r.q_float("min_liquidity_usd", min_liquidity_usd, lo=0)
        r.q_float("max_liquidity_usd", max_liquidity_usd, lo=0)
        r.q_float("min_volume_usd", min_volume_usd, lo=0)
        r.q_float("max_volume_usd", max_volume_usd, lo=0)
        r.q_float("min_market_cap_usd", min_market_cap_usd, lo=0)
        r.q_float("max_market_cap_usd", max_market_cap_usd, lo=0)
        r.q_float("min_fdv_usd", min_fdv_usd, lo=0)
        r.q_float("max_fdv_usd", max_fdv_usd, lo=0)
        r.q_int("min_age_seconds", min_age_seconds, lo=0)
        r.q_int("max_age_seconds", max_age_seconds, lo=0)
        r.q_int("min_score", min_score, lo=0, hi=100)
        r.q_int("max_score", max_score, lo=0, hi=100)
        r.q_int("min_holders", min_holders, lo=0)
        r.q_int("max_holders", max_holders, lo=0)
        r.q_bool("include_instances", include_instances)
        r.q_bool("include_market", include_market)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.TokenPage._from_json, options)

    def iter_tokens(self, *, q: str | None = None, chains: Sequence[str] | None = None, categories: Sequence[str] | None = None, sort: str | None = None, order: str | None = None, min_liquidity_usd: float | None = None, max_liquidity_usd: float | None = None, min_volume_usd: float | None = None, max_volume_usd: float | None = None, min_market_cap_usd: float | None = None, max_market_cap_usd: float | None = None, min_fdv_usd: float | None = None, max_fdv_usd: float | None = None, min_age_seconds: int | None = None, max_age_seconds: int | None = None, min_score: int | None = None, max_score: int | None = None, min_holders: int | None = None, max_holders: int | None = None, include_instances: bool | None = None, include_market: bool | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.TokenInfo]:
        """Every item of tokens, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.tokens(q=q, chains=chains, categories=categories, sort=sort, order=order, min_liquidity_usd=min_liquidity_usd, max_liquidity_usd=max_liquidity_usd, min_volume_usd=min_volume_usd, max_volume_usd=max_volume_usd, min_market_cap_usd=min_market_cap_usd, max_market_cap_usd=max_market_cap_usd, min_fdv_usd=min_fdv_usd, max_fdv_usd=max_fdv_usd, min_age_seconds=min_age_seconds, max_age_seconds=max_age_seconds, min_score=min_score, max_score=max_score, min_holders=min_holders, max_holders=max_holders, include_instances=include_instances, include_market=include_market, limit=limit, cursor=c, options=options), cursor, options)

    async def token_batch(self, *, items: Sequence[m.TokenBatchRef | Mapping[str, Any]], options: RequestOptions | None = None) -> m.TokenBatchResponse:
        """Resolve many tokens at once."""
        r = Call("tokenBatch", "POST")
        r.path_literal("tokens")
        r.path_literal("batch")
        r.check_items("items", items, lo=1, hi=200)
        r.body = encode_body({"items": items})
        return await self._send(r, m.TokenBatchResponse._from_json, options)

    async def token_holders(self, chain: str | int, address: str, *, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.TokenHolderPage:
        """Top holders of a token.

        Defaults: limit=10.
        """
        r = Call("tokenHolders", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("tokens")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("holders")
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.TokenHolderPage._from_json, options)

    def iter_token_holders(self, chain: str | int, address: str, *, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.TokenHolder]:
        """Every item of token_holders, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.token_holders(chain, address, limit=limit, cursor=c, options=options), cursor, options)

    async def token_traders(self, chain: str | int, address: str, *, sort: str | None = None, state: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.TokenTraderPage:
        """Wallets that traded a token, with their PNL on it.

        Defaults: sort="realized_pnl", state="any", limit=10.
        """
        r = Call("tokenTraders", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("tokens")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("traders")
        r.q_str("sort", sort)
        r.q_str("state", state)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.TokenTraderPage._from_json, options)

    def iter_token_traders(self, chain: str | int, address: str, *, sort: str | None = None, state: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.TokenTrader]:
        """Every item of token_traders, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.token_traders(chain, address, sort=sort, state=state, limit=limit, cursor=c, options=options), cursor, options)

    async def farms(self, *, chains: Sequence[str], q: str | None = None, factories: Sequence[str] | None = None, sort: str | None = None, order: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.FarmPage:
        """Yield farm screener.

        Defaults: sort="tvl", order="desc", limit=10.
        """
        r = Call("farms", "GET")
        r.path_literal("farms")
        r.q_list("chains", chains, required=True, lo=1, hi=8, item_lo=1, item_hi=32)
        r.q_str("q", q, hi=128)
        r.q_list("factories", factories, hi=32, item_lo=1, item_hi=128)
        r.q_str("sort", sort)
        r.q_str("order", order)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.FarmPage._from_json, options)

    def iter_farms(self, *, chains: Sequence[str], q: str | None = None, factories: Sequence[str] | None = None, sort: str | None = None, order: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.FarmInfo]:
        """Every item of farms, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.farms(chains=chains, q=q, factories=factories, sort=sort, order=order, limit=limit, cursor=c, options=options), cursor, options)

    async def farm(self, chain: str | int, address: str, *, options: RequestOptions | None = None) -> m.FarmInfo:
        """One yield farm."""
        r = Call("farm", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("farms")
        r.path_param("address", address, lo=1, hi=128)
        return await self._send(r, m.FarmInfo._from_json, options)

    async def wallets(self, *, chain: str, window: str | None = None, sort: str | None = None, order: str | None = None, min_total_pnl_usd: float | None = None, min_realized_pnl_usd: float | None = None, min_volume_usd: float | None = None, min_win_rate: float | None = None, min_trades: int | None = None, max_avg_hold_seconds: int | None = None, min_user_score: int | None = None, no_abuse_evidence: bool | None = None, only_copy_eligible: bool | None = None, exclude_bots: bool | None = None, tiers: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.WalletPage:
        """Rank traders on one chain.

        Defaults: window="30d", sort="total_pnl", order="desc", limit=10.
        """
        r = Call("wallets", "GET")
        r.path_literal("wallets")
        r.q_str("chain", chain, required=True, lo=1, hi=32)
        r.q_str("window", window)
        r.q_str("sort", sort)
        r.q_str("order", order)
        r.q_float("min_total_pnl_usd", min_total_pnl_usd)
        r.q_float("min_realized_pnl_usd", min_realized_pnl_usd)
        r.q_float("min_volume_usd", min_volume_usd)
        r.q_float("min_win_rate", min_win_rate, lo=0, hi=1)
        r.q_int("min_trades", min_trades)
        r.q_int("max_avg_hold_seconds", max_avg_hold_seconds)
        r.q_int("min_user_score", min_user_score, lo=0, hi=100)
        r.q_bool("no_abuse_evidence", no_abuse_evidence)
        r.q_bool("only_copy_eligible", only_copy_eligible)
        r.q_bool("exclude_bots", exclude_bots)
        r.q_list("tiers", tiers, hi=8, item_hi=32)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.WalletPage._from_json, options)

    def iter_wallets(self, *, chain: str, window: str | None = None, sort: str | None = None, order: str | None = None, min_total_pnl_usd: float | None = None, min_realized_pnl_usd: float | None = None, min_volume_usd: float | None = None, min_win_rate: float | None = None, min_trades: int | None = None, max_avg_hold_seconds: int | None = None, min_user_score: int | None = None, no_abuse_evidence: bool | None = None, only_copy_eligible: bool | None = None, exclude_bots: bool | None = None, tiers: Sequence[str] | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.WalletListItem]:
        """Every item of wallets, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.wallets(chain=chain, window=window, sort=sort, order=order, min_total_pnl_usd=min_total_pnl_usd, min_realized_pnl_usd=min_realized_pnl_usd, min_volume_usd=min_volume_usd, min_win_rate=min_win_rate, min_trades=min_trades, max_avg_hold_seconds=max_avg_hold_seconds, min_user_score=min_user_score, no_abuse_evidence=no_abuse_evidence, only_copy_eligible=only_copy_eligible, exclude_bots=exclude_bots, tiers=tiers, limit=limit, cursor=c, options=options), cursor, options)

    async def wallet_stats(self, *, chains: Sequence[str] | None = None, options: RequestOptions | None = None) -> m.WalletStats:
        """Trader population per chain."""
        r = Call("walletStats", "GET")
        r.path_literal("wallets")
        r.path_literal("stats")
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        return await self._send(r, m.WalletStats._from_json, options)

    async def wallet_labels_batch(self, *, chain: str | int, addresses: Sequence[str], options: RequestOptions | None = None) -> m.WalletLabelList:
        """Behaviour labels for many wallets."""
        r = Call("walletLabelsBatch", "POST")
        r.path_literal("wallets")
        r.path_literal("labels")
        r.path_literal("batch")
        r.check_items("addresses", addresses, lo=1, hi=200)
        r.body = encode_body({"chain": str(chain), "addresses": addresses})
        return await self._send(r, m.WalletLabelList._from_json, options)

    async def wallet_overview(self, address: str, *, chains: Sequence[str] | None = None, window: str | None = None, options: RequestOptions | None = None) -> m.WalletOverview:
        """One wallet across every chain it traded.

        Defaults: window="30d".
        """
        r = Call("walletOverview", "GET")
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("overview")
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_str("window", window)
        return await self._send(r, m.WalletOverview._from_json, options)

    async def leaderboard(self, *, scope: str, chain: str | None = None, chains: Sequence[str] | None = None, seasonal: bool | None = None, season: int | None = None, limit: int | None = None, options: RequestOptions | None = None) -> m.Leaderboard:
        """Chain and DEX protocol boards.

        Defaults: limit=50.
        """
        r = Call("leaderboard", "GET")
        r.path_literal("leaderboard")
        r.q_str("scope", scope, required=True)
        r.q_str("chain", chain, lo=1, hi=32)
        r.q_list("chains", chains, hi=32, item_lo=1, item_hi=32)
        r.q_bool("seasonal", seasonal)
        r.q_int("season", season, lo=0)
        r.q_int("limit", limit, lo=1, hi=200)
        return await self._send(r, m.Leaderboard._from_json, options)

    async def wallet_profile(self, chain: str | int, address: str, *, options: RequestOptions | None = None) -> m.WalletProfile:
        """Trader profile with metrics for every window."""
        r = Call("walletProfile", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        return await self._send(r, m.WalletProfile._from_json, options)

    async def wallet_positions(self, chain: str | int, address: str, *, state: str | None = None, sort: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.WalletPositionPage:
        """Open and closed positions of a wallet.

        Defaults: state="any", sort="token", limit=10.
        """
        r = Call("walletPositions", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("positions")
        r.q_str("state", state)
        r.q_str("sort", sort)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.WalletPositionPage._from_json, options)

    def iter_wallet_positions(self, chain: str | int, address: str, *, state: str | None = None, sort: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.WalletPosition]:
        """Every item of wallet_positions, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.wallet_positions(chain, address, state=state, sort=sort, limit=limit, cursor=c, options=options), cursor, options)

    async def wallet_trades(self, chain: str | int, address: str, *, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.WalletTradePage:
        """Raw trade history of a wallet.

        Defaults: limit=10.
        """
        r = Call("walletTrades", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("trades")
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.WalletTradePage._from_json, options)

    def iter_wallet_trades(self, chain: str | int, address: str, *, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.WalletTrade]:
        """Every item of wallet_trades, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.wallet_trades(chain, address, limit=limit, cursor=c, options=options), cursor, options)

    async def wallet_chart(self, chain: str | int, address: str, *, window: str | None = None, options: RequestOptions | None = None) -> m.WalletChart:
        """Wallet performance series — PNL and ROI.

        Defaults: window="30d".
        """
        r = Call("walletChart", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("chart")
        r.q_str("window", window)
        return await self._send(r, m.WalletChart._from_json, options)

    async def wallet_best_trades(self, chain: str | int, address: str, *, window: str | None = None, limit: int | None = None, options: RequestOptions | None = None) -> m.WalletBestTrades:
        """Best and worst closed trades of a wallet.

        Defaults: window="30d", limit=10.
        """
        r = Call("walletBestTrades", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("best-trades")
        r.q_str("window", window)
        r.q_int("limit", limit, lo=1, hi=100)
        return await self._send(r, m.WalletBestTrades._from_json, options)

    async def wallet_rounds(self, chain: str | int, address: str, *, token: str | None = None, state: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> m.WalletRoundPage:
        """Position rounds — one entry and exit cycle per row.

        Defaults: state="any", limit=10.
        """
        r = Call("walletRounds", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("rounds")
        r.q_str("token", token, lo=1, hi=128)
        r.q_str("state", state)
        r.q_int("limit", limit, lo=1, hi=100)
        r.q_str("cursor", cursor, hi=512)
        return await self._send(r, m.WalletRoundPage._from_json, options)

    def iter_wallet_rounds(self, chain: str | int, address: str, *, token: str | None = None, state: str | None = None, limit: int | None = None, cursor: str | None = None, options: RequestOptions | None = None) -> AsyncIterator[m.WalletPositionRound]:
        """Every item of wallet_rounds, fetching the next page only when the previous one is used up."""
        return apaginate(lambda c: self.wallet_rounds(chain, address, token=token, state=state, limit=limit, cursor=c, options=options), cursor, options)

    async def wallet_funding(self, chain: str | int, address: str, *, options: RequestOptions | None = None) -> m.WalletFunding:
        """Who funded a wallet."""
        r = Call("walletFunding", "GET")
        r.path_literal("chains")
        r.path_param("chain", chain, lo=1, hi=32)
        r.path_literal("wallets")
        r.path_param("address", address, lo=1, hi=128)
        r.path_literal("funding")
        return await self._send(r, m.WalletFunding._from_json, options)

    async def oracle_prices(self, *, ids: Sequence[str], options: RequestOptions | None = None) -> m.OraclePriceList:
        """Latest oracle prices by feed id."""
        r = Call("oraclePrices", "GET")
        r.path_literal("prices")
        r.q_list("ids", ids, required=True, lo=1, hi=100, item_lo=64, item_hi=66)
        return await self._send(r, m.OraclePriceList._from_json, options)

    async def oracle_prices_at(self, *, ids: Sequence[str], ts: int, options: RequestOptions | None = None) -> m.OraclePriceList:
        """Oracle prices at a past moment."""
        r = Call("oraclePricesAt", "GET")
        r.path_literal("prices")
        r.path_literal("at")
        r.q_list("ids", ids, required=True, lo=1, hi=100, item_lo=64, item_hi=66)
        r.q_int("ts", ts, required=True, lo=1)
        return await self._send(r, m.OraclePriceList._from_json, options)


OPERATIONS: tuple[tuple[str, str, str, str], ...] = (
    ("x402Discovery", "GET", "/.well-known/x402", "meta"),
    ("status", "GET", "/status", "meta"),
    ("key", "GET", "/key", "meta"),
    ("config", "GET", "/config", "meta"),
    ("chains", "GET", "/chains", "meta"),
    ("search", "GET", "/search", "dex"),
    ("pairs", "GET", "/pairs", "dex"),
    ("pair", "GET", "/chains/{chain}/pairs/{address}", "dex"),
    ("pairTrades", "GET", "/chains/{chain}/pairs/{address}/trades", "dex"),
    ("pairCandles", "GET", "/chains/{chain}/pairs/{address}/candles", "dex"),
    ("trending", "GET", "/trending", "dex"),
    ("pairsNew", "GET", "/pairs/new", "dex"),
    ("launchpadTokens", "GET", "/launchpads/tokens", "dex"),
    ("pairBatch", "POST", "/pairs/batch", "dex"),
    ("perps", "GET", "/perps", "dex"),
    ("perpHistory", "GET", "/perps/{market}/history", "dex"),
    ("perpLiquidations", "GET", "/perps/liquidations", "dex"),
    ("deployerTokens", "GET", "/deployers/{address}/tokens", "dex"),
    ("tokenByAddress", "GET", "/chains/{chain}/tokens/{address}", "token"),
    ("tokenPairs", "GET", "/chains/{chain}/tokens/{address}/pairs", "token"),
    ("tokenVerdict", "GET", "/chains/{chain}/tokens/{address}/verdict", "token"),
    ("tokenVerdictProof", "GET", "/chains/{chain}/tokens/{address}/proof", "token"),
    ("tokenBrief", "GET", "/chains/{chain}/tokens/{address}/brief", "token"),
    ("tokenByID", "GET", "/tokens/{id}", "token"),
    ("tokenBySlug", "GET", "/tokens/by-slug/{slug}", "token"),
    ("tokens", "GET", "/tokens", "token"),
    ("tokenBatch", "POST", "/tokens/batch", "token"),
    ("tokenHolders", "GET", "/chains/{chain}/tokens/{address}/holders", "token"),
    ("tokenTraders", "GET", "/chains/{chain}/tokens/{address}/traders", "token"),
    ("farms", "GET", "/farms", "farm"),
    ("farm", "GET", "/chains/{chain}/farms/{address}", "farm"),
    ("wallets", "GET", "/wallets", "wallet"),
    ("walletStats", "GET", "/wallets/stats", "wallet"),
    ("walletLabelsBatch", "POST", "/wallets/labels/batch", "wallet"),
    ("walletOverview", "GET", "/wallets/{address}/overview", "wallet"),
    ("leaderboard", "GET", "/leaderboard", "wallet"),
    ("walletProfile", "GET", "/chains/{chain}/wallets/{address}", "wallet"),
    ("walletPositions", "GET", "/chains/{chain}/wallets/{address}/positions", "wallet"),
    ("walletTrades", "GET", "/chains/{chain}/wallets/{address}/trades", "wallet"),
    ("walletChart", "GET", "/chains/{chain}/wallets/{address}/chart", "wallet"),
    ("walletBestTrades", "GET", "/chains/{chain}/wallets/{address}/best-trades", "wallet"),
    ("walletRounds", "GET", "/chains/{chain}/wallets/{address}/rounds", "wallet"),
    ("walletFunding", "GET", "/chains/{chain}/wallets/{address}/funding", "wallet"),
    ("oraclePrices", "GET", "/prices", "oracle"),
    ("oraclePricesAt", "GET", "/prices/at", "oracle"),
)
